name: Update gist with Steam Playtime

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
    
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  
jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: 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  
          GIST_ID: 8bf56353bcb3a8e798b55b546b9619cf
          STEAM_API_KEY: 7B27F81FB0A67D96B2ED2854A08A0488
          STEAM_ID: 76561199383788952
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Update-gist
      run:  go run ./cmd/box/main.go

